#!/usr/bin/env bash
# Auto-generated by da:devsh — Port-hashed dev server launcher
# Project: dodam
# Type: nextjs
# Generated: 2026-04-09

set -e

PORT=${1:-6774}
PROJECT_TYPE="nextjs"

echo "🚀 Starting dodam on port $PORT..."

# Kill any existing process on the port
if lsof -ti:$PORT >/dev/null 2>&1; then
  echo "⚠️  Killing existing process on port $PORT..."
  lsof -ti:$PORT | xargs kill -9 2>/dev/null || true
  sleep 1
fi

# Load environment variables
[ -f .env.local ] && export $(grep -v '^#' .env.local | xargs) 2>/dev/null || true
[ -f .env ] && export $(grep -v '^#' .env | xargs) 2>/dev/null || true

# Fix incompatible Next.js config (output: "export" breaks next dev)
for cfg in next.config.ts next.config.mjs next.config.js; do
  if [ -f "$cfg" ] && grep -q 'output.*export' "$cfg"; then
    echo "⚠️  Removing output: \"export\" from $cfg (incompatible with next dev)"
    sed -i "" "/output.*['\"]export['\"]/d" "$cfg"
    sed -i "" "/unoptimized.*true/d" "$cfg"
  fi
done

# Install dependencies if needed
[ ! -d "node_modules" ] && echo "📦 Installing dependencies..." && npm install

# Start the development server
echo "🔧 Starting $PROJECT_TYPE dev server on port $PORT..."
exec npx next dev --turbopack -p $PORT
